Review functionality for hosts, guests and properties
framgia/ph-airbnb-rails-shania pull request #17
Opened 2019-08-31 11:59 UTC by shaniajubelag

[Commands]
• docker-compose exec web bundle install
• docker-compose down
• docker-compose up --build -d
• docker-compose exec web rails db:migrate:reset

[Pre-conditions]
• Login as two users (advisable: open two browsers at the same time, each browser with a different account)
• Click the “Become a host” button located on the header (do this for at last one of the users)
• Fill in the forms
• Go to the user that didn’t make a Property and try to reserve a property
• Access the property route (type: http://localhost:3002/properties/1)
• Fill in forms (enter start date and end date)
• Click “Book now”
• Review the host by accessing "Your Trips"
• Fill in forms
• Login as the Host
• Review the guest by accessing "Your Reservations"
• Fill in the Form

[Expected Output]
• Guest can review a room after reservation is done with star rating
• Guest can delete their own comment 
• Host can review a guest after reservation is done with star rating
• Host can delete their own comment
• Review of Property can be seen when you access Property profile page

[Notes]
• N/A

2019-09-02 09:09 UTC, charlotteds requested changes
Notes:
- Property show page output (Reviews section):
![image](https://user-images.githubusercontent.com/20994464/64095786-654d6100-cd92-11e9-9672-9781e7c899e5.png)

- Example Expected Output:
![image](https://user-images.githubusercontent.com/20994464/64095853-9e85d100-cd92-11e9-8247-d5b7be3fdf77.png)

- Change link when review is submitted:
![image](https://user-images.githubusercontent.com/20994464/64099037-e872b500-cd9a-11e9-92c8-b72c3f809214.png)
- Don't let user review the property more than once (Expected Output):
![image](https://user-images.githubusercontent.com/20994464/64099203-469f9800-cd9b-11e9-9924-f5f549737e76.png)
- Action ID/Type is not saved to DB:
![image](https://user-images.githubusercontent.com/20994464/64103235-58396d80-cda4-11e9-94cd-b95899e0827c.png)

2019-09-02 12:09 UTC, shaniajubelag commented
I removed the "relationship" table and the "review action polymorphic relationship" because I am not using them.

2019-09-03 07:33 UTC, charlotteds reviewed
Notes:
- As Host, user should not see own star rating for guest. Display reviews of the guests only.
![image](https://user-images.githubusercontent.com/20994464/64152455-3f41c280-ce5f-11e9-9d32-59639e722f2a.png)

- Review button missing on guest side:
![image](https://user-images.githubusercontent.com/20994464/64152587-93e53d80-ce5f-11e9-9631-0308bd1c3136.png)

2019-09-04 09:57 UTC, charlotteds approved these changes

2019-09-04 09:57 UTC, merged